SELECT a.id_product,#(lf)m.name as Marca,#(lf)a.ean13 AS EAN13,#(lf)a.reference as Referencia_PS,#(lf)b.name as Nombre_Producto,#(lf)cl.name  AS Categoria,#(lf)a.minimal_quantity As Mínimo_Compra,#(lf)a.price as Precio_Mayorista,#(lf)ifnull(#(lf)ROUND((SELECT sp.price#(lf)FROM ps_specific_price sp#(lf)left join ps_group_lang gl on sp.id_group=gl.id_group#(lf)where a.active = 1 #'Estado_(1=Activo, 0=Inactivo)'# #(lf)and a.id_product = sp.id_product#(lf)and sp.id_customer = 0#(lf)and gl.name = 'B2B_20%_DESCUENTO'#(lf)and sp.reduction_type = 'amount') * 0.8,0), Round(a.price * 0.8,0) )AS 'B2B 20% DESCUENTO' ,#(lf)ifnull(#(lf)ROUND((SELECT sp.price#(lf)FROM ps_specific_price sp#(lf)left join ps_group_lang gl on sp.id_group=gl.id_group#(lf)where a.active = 1 #'Estado_(1=Activo, 0=Inactivo)'# #(lf)and a.id_product = sp.id_product#(lf)and sp.id_customer = 0#(lf)and gl.name = 'B2B_10%_DESCUENTO'#(lf)and sp.reduction_type = 'amount') * 0.9,0), Round(a.price * 0.9,0) )AS 'B2B 10% DESCUENTO' ,#(lf)if(cl.name='Otras Marcas' or 'Manare_' or a.id_product = 128 or a.id_product = 136 or a.id_product = 137,a.price,Round(a.price * 0.95,0)) AS 'B2B 5% DESCUENTO',#(lf)if(cl.name='Otras Marcas'or 'Manare_' or a.id_product = 128 or a.id_product = 136 or a.id_product = 137,a.price,Round(a.price * 0.97,0)) AS 'B2B 3% DESCUENTO',#(lf)sav.quantity  AS Saldo_disponible_PS,#(lf)a.width as Ancho,#(lf)a.height As Altura,#(lf)a.depth as Profundidad,#(lf)a.weight as Peso,#(lf)(SELECT fvl.value#(lf)FROM ps_feature_product fp#(lf)left join ps_feature_lang fl on fp.id_feature = fl.id_feature#(lf)left join ps_feature_value_lang fvl on fp.id_feature_value=fvl.id_feature_value#(lf)where fl.name = 'Duración' and (a.id_product = fp.id_product)) As Duracion,#(lf)(SELECT fvl.value#(lf)FROM ps_feature_product fp#(lf)left join ps_feature_lang fl on fp.id_feature = fl.id_feature#(lf)left join ps_feature_value_lang fvl on fp.id_feature_value=fvl.id_feature_value#(lf)where fl.name = 'Valor de Venta Sugerido' and (a.id_product = fp.id_product)) As 'Valor_de_Venta_Sugerido',#(lf)a.date_upd As Fecha_última_actualización,#(lf)
a.active as 'Estado_(1=Activo, 0=Inactivo)',#(lf)
mc.id_minpurchase_configuration as 'id_minpurchase_configuration (MIN_MAX)',#(lf)
mc.name as 'name (MIN_MAX)',#(lf)
mc.minimum_quantity as 'minimum_quantity (MIN_MAX)',#(lf)
mc.maximum_quantity as 'maximum_quantity (MIN_MAX)',#(lf)
mc.multiple as 'multiple (MIN_MAX)',#(lf)
mc.multiple_qty as 'multiple_qty (MIN_MAX)',#(lf)
mc.products AS 'PS_ID_PRODUCT (MIN_MAX)',#(lf)
mc.date_add as 'date_add (MIN_MAX)',#(lf)
mc.date_upd as 'date_upd (MIN_MAX)',#(lf)
mc.active as 'Estado (MIN_MAX)'#(lf)
FROM ps_product a#(lf)
left join ps_product_lang b on (b.id_product = a.id_product)#(lf)
JOIN ps_product_shop sa ON (a.id_product = sa.id_product AND sa.id_shop = 1) #(lf)
LEFT JOIN ps_category_lang cl ON (sa.id_category_default = cl.id_category AND cl.id_lang = 1 AND cl.id_shop = 1) #(lf)
LEFT JOIN ps_stock_available sav ON (sav.id_product = a.id_product AND sav.id_product_attribute = 0 AND sav.id_shop = 1  AND sav.id_shop_group = 0 )#(lf)
LEFT JOIN ps_minpurchase_configuration mc on mc.products = a.id_product#(lf)
LEFT JOIN ps_manufacturer m ON (m.id_manufacturer = a.id_manufacturer)#(lf)
order by 4;